- name: allocate requirements.txt
  copy: src=requirements.txt dest=/home/vagrant/

- name: install pip dependency
  shell: |
    /usr/local/bin/pip3 install -r /home/vagrant/requirements.txt
  args:
    creates: /usr/local/lib/python3.3/site-packages/requests
