---
- name: install nginx repo
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm state=present

- name: install nginx
  yum: name=nginx state=latest

- name: default.conf allocate
  template: src=default.conf.j2 dest={{conf_dir}}/default.conf
  notify: restart nginx

- name: virtual.conf allocate
  template: src=virtual.conf.j2 dest={{conf_dir}}/virtual.conf
  notify: restart nginx

- name: ssl files allocate
  copy: src=ssl dest={{ssl_dir}}
  notify: restart nginx

- name: .htpasswd allocate
  copy: src=_htpasswd dest={{htpasswd_dir}}/.htpasswd
  notify: restart nginx
